CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_users_email_normalized
        CHECK (email = LOWER(BTRIM(email)) AND email <> ''),
    CONSTRAINT ck_users_display_name_not_blank
        CHECK (BTRIM(display_name) <> ''),
    CONSTRAINT ck_users_status
        CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE UNIQUE INDEX ux_users_email_lower ON users (LOWER(email));

CREATE TABLE households (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    base_currency VARCHAR(3) NOT NULL DEFAULT 'KRW',
    timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Seoul',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_households_name_not_blank
        CHECK (BTRIM(name) <> ''),
    CONSTRAINT ck_households_base_currency
        CHECK (base_currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_households_timezone_not_blank
        CHECK (BTRIM(timezone) <> '')
);

CREATE TABLE household_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(16) NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_household_members_household
        FOREIGN KEY (household_id) REFERENCES households (id),
    CONSTRAINT fk_household_members_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_household_members_household_user
        UNIQUE (household_id, user_id),
    CONSTRAINT ck_household_members_role
        CHECK (role IN ('OWNER', 'MEMBER'))
);

CREATE UNIQUE INDEX ux_household_members_single_owner
    ON household_members (household_id)
    WHERE role = 'OWNER';

CREATE INDEX ix_household_members_user ON household_members (user_id);
