ALTER TABLE household_members
    ADD CONSTRAINT uq_household_members_id_household
        UNIQUE (id, household_id);

CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    institution VARCHAR(100),
    type VARCHAR(24) NOT NULL,
    nature VARCHAR(16) NOT NULL,
    ownership VARCHAR(16) NOT NULL,
    owner_member_id BIGINT,
    opening_balance BIGINT NOT NULL DEFAULT 0,
    opening_balance_as_of DATE NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'KRW',
    last_four VARCHAR(4),
    savings_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_accounts_household
        FOREIGN KEY (household_id) REFERENCES households (id),
    CONSTRAINT fk_accounts_owner_member_household
        FOREIGN KEY (owner_member_id, household_id)
        REFERENCES household_members (id, household_id),
    CONSTRAINT uq_accounts_id_household
        UNIQUE (id, household_id),
    CONSTRAINT ck_accounts_name_not_blank
        CHECK (BTRIM(name) <> ''),
    CONSTRAINT ck_accounts_institution_not_blank
        CHECK (institution IS NULL OR BTRIM(institution) <> ''),
    CONSTRAINT ck_accounts_type
        CHECK (type IN ('CHECKING', 'SAVINGS', 'CASH', 'CREDIT_CARD', 'OTHER')),
    CONSTRAINT ck_accounts_nature
        CHECK (nature IN ('ASSET', 'LIABILITY')),
    CONSTRAINT ck_accounts_ownership
        CHECK (ownership IN ('PERSONAL', 'SHARED')),
    CONSTRAINT ck_accounts_owner_scope
        CHECK (
            (ownership = 'PERSONAL' AND owner_member_id IS NOT NULL)
            OR (ownership = 'SHARED' AND owner_member_id IS NULL)
        ),
    CONSTRAINT ck_accounts_currency_krw
        CHECK (currency = 'KRW'),
    CONSTRAINT ck_accounts_last_four
        CHECK (last_four IS NULL OR last_four ~ '^[0-9]{4}$'),
    CONSTRAINT ck_accounts_savings_asset
        CHECK (NOT savings_enabled OR nature = 'ASSET'),
    CONSTRAINT ck_accounts_sort_order
        CHECK (sort_order >= 0)
);

CREATE INDEX ix_accounts_household_active_sort
    ON accounts (household_id, sort_order, id)
    WHERE archived_at IS NULL;

CREATE TABLE category_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(16) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_category_groups_household
        FOREIGN KEY (household_id) REFERENCES households (id),
    CONSTRAINT uq_category_groups_id_household
        UNIQUE (id, household_id),
    CONSTRAINT uq_category_groups_id_household_type
        UNIQUE (id, household_id, type),
    CONSTRAINT ck_category_groups_name_not_blank
        CHECK (BTRIM(name) <> ''),
    CONSTRAINT ck_category_groups_type
        CHECK (type IN ('INCOME', 'EXPENSE')),
    CONSTRAINT ck_category_groups_sort_order
        CHECK (sort_order >= 0)
);

CREATE INDEX ix_category_groups_household_active_sort
    ON category_groups (household_id, type, sort_order, id)
    WHERE archived_at IS NULL;

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id BIGINT NOT NULL,
    group_id BIGINT,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(16) NOT NULL,
    icon_key VARCHAR(64),
    color_key VARCHAR(64),
    sort_order INTEGER NOT NULL DEFAULT 0,
    archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_categories_household
        FOREIGN KEY (household_id) REFERENCES households (id),
    CONSTRAINT fk_categories_group_household_type
        FOREIGN KEY (group_id, household_id, type)
        REFERENCES category_groups (id, household_id, type),
    CONSTRAINT uq_categories_id_household
        UNIQUE (id, household_id),
    CONSTRAINT uq_categories_id_household_type
        UNIQUE (id, household_id, type),
    CONSTRAINT ck_categories_name_not_blank
        CHECK (BTRIM(name) <> ''),
    CONSTRAINT ck_categories_type
        CHECK (type IN ('INCOME', 'EXPENSE')),
    CONSTRAINT ck_categories_icon_key_not_blank
        CHECK (icon_key IS NULL OR BTRIM(icon_key) <> ''),
    CONSTRAINT ck_categories_color_key_not_blank
        CHECK (color_key IS NULL OR BTRIM(color_key) <> ''),
    CONSTRAINT ck_categories_sort_order
        CHECK (sort_order >= 0)
);

CREATE UNIQUE INDEX ux_categories_active_name
    ON categories (household_id, type, LOWER(name))
    WHERE archived_at IS NULL;

CREATE INDEX ix_categories_household_active_sort
    ON categories (household_id, type, sort_order, id)
    WHERE archived_at IS NULL;

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id BIGINT NOT NULL,
    type VARCHAR(16) NOT NULL,
    amount BIGINT NOT NULL,
    scope VARCHAR(16),
    owner_member_id BIGINT,
    payer_member_id BIGINT,
    category_id BIGINT,
    occurred_at TIMESTAMPTZ NOT NULL,
    memo VARCHAR(500),
    adjustment_type VARCHAR(16) NOT NULL,
    reverses_transaction_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT fk_transactions_household
        FOREIGN KEY (household_id) REFERENCES households (id),
    CONSTRAINT fk_transactions_owner_member_household
        FOREIGN KEY (owner_member_id, household_id)
        REFERENCES household_members (id, household_id),
    CONSTRAINT fk_transactions_payer_member_household
        FOREIGN KEY (payer_member_id, household_id)
        REFERENCES household_members (id, household_id),
    CONSTRAINT fk_transactions_category_household_type
        FOREIGN KEY (category_id, household_id, type)
        REFERENCES categories (id, household_id, type),
    CONSTRAINT fk_transactions_reversal_household
        FOREIGN KEY (reverses_transaction_id, household_id)
        REFERENCES transactions (id, household_id),
    CONSTRAINT fk_transactions_created_by_household
        FOREIGN KEY (created_by, household_id)
        REFERENCES household_members (id, household_id),
    CONSTRAINT fk_transactions_updated_by_household
        FOREIGN KEY (updated_by, household_id)
        REFERENCES household_members (id, household_id),
    CONSTRAINT fk_transactions_deleted_by_household
        FOREIGN KEY (deleted_by, household_id)
        REFERENCES household_members (id, household_id),
    CONSTRAINT uq_transactions_id_household
        UNIQUE (id, household_id),
    CONSTRAINT ck_transactions_type
        CHECK (type IN ('INCOME', 'EXPENSE', 'TRANSFER')),
    CONSTRAINT ck_transactions_amount_positive
        CHECK (amount > 0),
    CONSTRAINT ck_transactions_scope
        CHECK (scope IS NULL OR scope IN ('PERSONAL', 'SHARED')),
    CONSTRAINT ck_transactions_scope_fields
        CHECK (
            (type IN ('INCOME', 'EXPENSE') AND category_id IS NOT NULL AND (
                (scope = 'PERSONAL' AND owner_member_id IS NOT NULL)
                OR (scope = 'SHARED' AND owner_member_id IS NULL)
            ))
            OR (type = 'TRANSFER' AND scope IS NULL AND owner_member_id IS NULL
                AND payer_member_id IS NULL AND category_id IS NULL)
        ),
    CONSTRAINT ck_transactions_adjustment_type
        CHECK (adjustment_type IN ('NORMAL', 'REFUND')),
    CONSTRAINT ck_transactions_adjustment_reference
        CHECK (
            (adjustment_type = 'NORMAL' AND reverses_transaction_id IS NULL)
            OR (type = 'EXPENSE' AND adjustment_type = 'REFUND'
                AND reverses_transaction_id IS NOT NULL)
        ),
    CONSTRAINT ck_transactions_memo_not_blank
        CHECK (memo IS NULL OR BTRIM(memo) <> ''),
    CONSTRAINT ck_transactions_version
        CHECK (version >= 0),
    CONSTRAINT ck_transactions_deleted_audit
        CHECK (
            (deleted_at IS NULL AND deleted_by IS NULL)
            OR (deleted_at IS NOT NULL AND deleted_by IS NOT NULL)
        )
);

CREATE INDEX ix_transactions_household_occurred
    ON transactions (household_id, occurred_at DESC, id DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX ix_transactions_household_owner
    ON transactions (household_id, owner_member_id)
    WHERE deleted_at IS NULL;

CREATE INDEX ix_transactions_household_category
    ON transactions (household_id, category_id)
    WHERE deleted_at IS NULL;
