CREATE TABLE transaction_account_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id BIGINT NOT NULL,
    transaction_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    entry_role VARCHAR(16) NOT NULL,
    balance_delta BIGINT NOT NULL,
    CONSTRAINT fk_transaction_account_entries_household
        FOREIGN KEY (household_id) REFERENCES households (id),
    CONSTRAINT fk_transaction_account_entries_transaction_household
        FOREIGN KEY (transaction_id, household_id)
        REFERENCES transactions (id, household_id),
    CONSTRAINT fk_transaction_account_entries_account_household
        FOREIGN KEY (account_id, household_id)
        REFERENCES accounts (id, household_id),
    CONSTRAINT uq_transaction_account_entries_transaction_role
        UNIQUE (transaction_id, entry_role),
    CONSTRAINT ck_transaction_account_entries_role
        CHECK (entry_role IN ('PRIMARY', 'SOURCE', 'DESTINATION')),
    CONSTRAINT ck_transaction_account_entries_delta_nonzero
        CHECK (balance_delta <> 0)
);

CREATE INDEX ix_transaction_account_entries_account
    ON transaction_account_entries (household_id, account_id);
