CREATE TABLE budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id BIGINT NOT NULL,
    budget_month DATE NOT NULL,
    scope VARCHAR(16) NOT NULL,
    owner_member_id BIGINT,
    category_id BIGINT,
    amount BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_budgets_household
        FOREIGN KEY (household_id) REFERENCES households (id),
    CONSTRAINT fk_budgets_owner_member_household
        FOREIGN KEY (owner_member_id, household_id)
        REFERENCES household_members (id, household_id),
    CONSTRAINT fk_budgets_category_household
        FOREIGN KEY (category_id, household_id)
        REFERENCES categories (id, household_id),
    CONSTRAINT uq_budgets_id_household
        UNIQUE (id, household_id),
    CONSTRAINT uq_budgets_identity
        UNIQUE NULLS NOT DISTINCT (
            household_id,
            budget_month,
            scope,
            owner_member_id,
            category_id
        ),
    CONSTRAINT ck_budgets_month_first_day
        CHECK (EXTRACT(DAY FROM budget_month) = 1),
    CONSTRAINT ck_budgets_scope
        CHECK (scope IN ('HOUSEHOLD', 'PERSONAL', 'SHARED')),
    CONSTRAINT ck_budgets_owner_scope
        CHECK (
            (scope = 'PERSONAL' AND owner_member_id IS NOT NULL)
            OR (scope IN ('HOUSEHOLD', 'SHARED') AND owner_member_id IS NULL)
        ),
    CONSTRAINT ck_budgets_amount_nonnegative
        CHECK (amount >= 0),
    CONSTRAINT ck_budgets_version
        CHECK (version >= 0)
);
