CREATE TABLE recurring_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(16) NOT NULL,
    amount BIGINT NOT NULL,
    scope VARCHAR(16),
    owner_member_id BIGINT,
    payer_member_id BIGINT,
    category_id BIGINT,
    memo VARCHAR(500),
    frequency VARCHAR(16) NOT NULL,
    interval_value INTEGER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    scheduled_local_time TIME NOT NULL,
    auto_post BOOLEAN NOT NULL DEFAULT TRUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    next_recurrence_date DATE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL,
    CONSTRAINT fk_recurring_transactions_household
        FOREIGN KEY (household_id) REFERENCES households (id),
    CONSTRAINT fk_recurring_transactions_owner_member_household
        FOREIGN KEY (owner_member_id, household_id)
        REFERENCES household_members (id, household_id),
    CONSTRAINT fk_recurring_transactions_payer_member_household
        FOREIGN KEY (payer_member_id, household_id)
        REFERENCES household_members (id, household_id),
    CONSTRAINT fk_recurring_transactions_category_household_type
        FOREIGN KEY (category_id, household_id, type)
        REFERENCES categories (id, household_id, type),
    CONSTRAINT fk_recurring_transactions_created_by_household
        FOREIGN KEY (created_by, household_id)
        REFERENCES household_members (id, household_id),
    CONSTRAINT fk_recurring_transactions_updated_by_household
        FOREIGN KEY (updated_by, household_id)
        REFERENCES household_members (id, household_id),
    CONSTRAINT uq_recurring_transactions_id_household
        UNIQUE (id, household_id),
    CONSTRAINT ck_recurring_transactions_name_not_blank
        CHECK (BTRIM(name) <> ''),
    CONSTRAINT ck_recurring_transactions_type
        CHECK (type IN ('INCOME', 'EXPENSE', 'TRANSFER')),
    CONSTRAINT ck_recurring_transactions_amount_positive
        CHECK (amount > 0),
    CONSTRAINT ck_recurring_transactions_scope
        CHECK (scope IS NULL OR scope IN ('PERSONAL', 'SHARED')),
    CONSTRAINT ck_recurring_transactions_template_fields
        CHECK (
            (type = 'INCOME' AND category_id IS NOT NULL AND payer_member_id IS NULL AND (
                (scope = 'PERSONAL' AND owner_member_id IS NOT NULL)
                OR (scope = 'SHARED' AND owner_member_id IS NULL)
            ))
            OR (type = 'EXPENSE' AND category_id IS NOT NULL AND (
                (scope = 'PERSONAL' AND owner_member_id IS NOT NULL)
                OR (scope = 'SHARED' AND owner_member_id IS NULL)
            ))
            OR (type = 'TRANSFER' AND scope IS NULL AND owner_member_id IS NULL
                AND payer_member_id IS NULL AND category_id IS NULL)
        ),
    CONSTRAINT ck_recurring_transactions_memo_not_blank
        CHECK (memo IS NULL OR BTRIM(memo) <> ''),
    CONSTRAINT ck_recurring_transactions_frequency
        CHECK (frequency IN ('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY')),
    CONSTRAINT ck_recurring_transactions_interval_positive
        CHECK (interval_value > 0),
    CONSTRAINT ck_recurring_transactions_date_range
        CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT ck_recurring_transactions_auto_post
        CHECK (auto_post),
    CONSTRAINT ck_recurring_transactions_next_date
        CHECK (
            next_recurrence_date IS NULL
            OR (next_recurrence_date >= start_date
                AND (end_date IS NULL OR next_recurrence_date <= end_date))
        ),
    CONSTRAINT ck_recurring_transactions_version
        CHECK (version >= 0)
);

CREATE TABLE recurring_transaction_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id BIGINT NOT NULL,
    recurring_transaction_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    entry_role VARCHAR(16) NOT NULL,
    CONSTRAINT fk_recurring_transaction_accounts_household
        FOREIGN KEY (household_id) REFERENCES households (id),
    CONSTRAINT fk_recurring_transaction_accounts_rule_household
        FOREIGN KEY (recurring_transaction_id, household_id)
        REFERENCES recurring_transactions (id, household_id),
    CONSTRAINT fk_recurring_transaction_accounts_account_household
        FOREIGN KEY (account_id, household_id)
        REFERENCES accounts (id, household_id),
    CONSTRAINT uq_recurring_transaction_accounts_rule_role
        UNIQUE (recurring_transaction_id, entry_role),
    CONSTRAINT ck_recurring_transaction_accounts_role
        CHECK (entry_role IN ('PRIMARY', 'SOURCE', 'DESTINATION'))
);

ALTER TABLE transactions
    ADD COLUMN generated_from_recurring_id BIGINT,
    ADD COLUMN recurrence_date DATE,
    ADD CONSTRAINT fk_transactions_generated_recurring_household
        FOREIGN KEY (generated_from_recurring_id, household_id)
        REFERENCES recurring_transactions (id, household_id),
    ADD CONSTRAINT ck_transactions_generated_pair
        CHECK (
            (generated_from_recurring_id IS NULL AND recurrence_date IS NULL)
            OR (generated_from_recurring_id IS NOT NULL AND recurrence_date IS NOT NULL)
        ),
    ADD CONSTRAINT ck_transactions_generated_normal
        CHECK (generated_from_recurring_id IS NULL OR adjustment_type = 'NORMAL'),
    ADD CONSTRAINT uq_transactions_recurring_occurrence
        UNIQUE (generated_from_recurring_id, recurrence_date);

CREATE INDEX ix_recurring_transactions_due
    ON recurring_transactions (next_recurrence_date, id)
    WHERE active AND next_recurrence_date IS NOT NULL;

CREATE INDEX ix_recurring_transaction_accounts_account
    ON recurring_transaction_accounts (household_id, account_id);
