CREATE TABLE goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id BIGINT NOT NULL,
    type VARCHAR(16) NOT NULL,
    name VARCHAR(100) NOT NULL,
    target_amount BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL,
    CONSTRAINT fk_goals_household
        FOREIGN KEY (household_id) REFERENCES households (id),
    CONSTRAINT fk_goals_created_by_household
        FOREIGN KEY (created_by, household_id)
        REFERENCES household_members (id, household_id),
    CONSTRAINT fk_goals_updated_by_household
        FOREIGN KEY (updated_by, household_id)
        REFERENCES household_members (id, household_id),
    CONSTRAINT uq_goals_id_household
        UNIQUE (id, household_id),
    CONSTRAINT ck_goals_type
        CHECK (type IN ('MARRIAGE', 'CUSTOM')),
    CONSTRAINT ck_goals_name_not_blank
        CHECK (BTRIM(name) <> ''),
    CONSTRAINT ck_goals_target_amount_positive
        CHECK (target_amount > 0),
    CONSTRAINT ck_goals_version
        CHECK (version >= 0)
);

CREATE UNIQUE INDEX ux_goals_household_marriage
    ON goals (household_id)
    WHERE type = 'MARRIAGE';

CREATE TABLE goal_accounts (
    goal_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    household_id BIGINT NOT NULL,
    starting_balance BIGINT NOT NULL,
    linked_at TIMESTAMPTZ NOT NULL,
    linked_by BIGINT NOT NULL,
    PRIMARY KEY (goal_id, account_id),
    CONSTRAINT fk_goal_accounts_goal_household
        FOREIGN KEY (goal_id, household_id)
        REFERENCES goals (id, household_id),
    CONSTRAINT fk_goal_accounts_account_household
        FOREIGN KEY (account_id, household_id)
        REFERENCES accounts (id, household_id),
    CONSTRAINT fk_goal_accounts_linked_by_household
        FOREIGN KEY (linked_by, household_id)
        REFERENCES household_members (id, household_id),
    CONSTRAINT uq_goal_accounts_account
        UNIQUE (account_id)
);
